### ISSUE TITLE
What needs to be done?

### ISSUE THREAD

**Issue by mackbrowne** [sibelius/ngTagsInputES6#1]
hey @sibelius , I'd love to get this working.  Taking a look at [this](https://github.com/orizens/angular-es6-styleguide) at the moment, might take a stab at it later today.  How far along are you?  Anything specific that is incomplete that I can help with?

**Comment by sibelius** [comment]
I'm following this guide here - https://github.com/toddmotto/angular-styleguide

I've just updated the `src` folder with my last changes (https://github.com/sibelius/ngTagsInputES6/commit/d261c109ba177419f768c66fd47853d26837ab3e)

The ideia is to add these files to your project

``` js
import './tagsInput/ng-tags-input.css';
import './tagsInput/ng-tags-input.bootstrap.css';
import tagsInput from './tagsInput';

angular.module('awesomeApp', [
    tagsInput.name,
])
```
- tagsInput is the `src` folder of this repo

add `tags-input` to a .html or .jade file to test if this is working properly

you could also try to move test folder from https://github.com/mbenford/ngTagsInput, and see if they r still passing

**Comment by mackbrowne** [comment]
Hello, i got the main repo working through npm.  I used 

`
import ngTagsInput from 'ng-tags-input';
`

then inject it using the actual model name

`
export default angular.module(name, [ 'ngTagsInput'])
`
